name: Flake Check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest # x86_64-linux
          - macos-latest # aarch64-darwin
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check -L
